name: "ftn-raspored-dev"
services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - frontend
      - api
    ports:
      - "8001:80"
    networks:
      - raspored
    volumes:
      - ./nginx:/etc/nginx:ro
    restart: always
  backend:
    build: ../backend
    volumes:
      - database:/var/db:rw
    restart: "no"
  api:
    build:
      context: ../api
      dockerfile: ../api/dev.Dockerfile
    depends_on:
      backend:
        condition: service_completed_successfully
    ports:
      - "10000:10000"
    volumes:
      - database:/var/db:ro
      - ../api:/usr/src/app
    networks:
      - raspored
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/dev.Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ../frontend/src:/usr/src/app/src
    networks:
      - raspored
networks:
  raspored:
volumes:
  database:
