version: "3.7"
name: ftn-raspored
services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - frontend
      - api
    ports:
      - "8000:80"
    networks:
      - raspored
    volumes:
      - ./nginx:/etc/nginx:ro
    restart: always
  frontend:
    build: ../frontend
    networks:
      - raspored
    restart: "no"
  api:
    build: ../api
    depends_on:
      backend:
        condition: service_completed_successfully
    volumes:
      - database:/var/db:ro
    networks:
      - raspored
    restart: always
  backend:
    build: ../backend
    volumes:
      - database:/var/db:rw
    restart: "no"
networks:
  raspored:
volumes:
  database:
